language: java

jdk: openjdk11

env:
  global:
    - MAVEN_OPTS="-Xmx15g"
  matrix:
    - TEST=RunHamburgScenarioTest
script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
